### ISSUE TITLE
Support dylib

### ISSUE THREAD

**Issue by brendanlong** [kennknowles/ocaml-freetds#12]
See https://github.com/paurkedal/ocaml-caqti/issues/12

They  said that hte META file is missing plugin(byte) and plugin(native) stanzas, but I think we also need to add a build for a .cmxs file, which I don't really know how to do.

One recommended solution is to use Dune/jbuilder instead of whatever we currently use to make the META file: https://github.com/paurkedal/ocaml-caqti/issues/12#issuecomment-379544209

**Comment by Chris00** [comment]
We'd like to move to Dune/jbuilder eventually.  It is just lack of time...
