### ISSUE TITLE
A new opam release?

### ISSUE THREAD

**Issue by brendanlong** [kennknowles/ocaml-freetds#18]
Once #16  and #17  are merged, mind if I setup a new opam release for version 0.5.2? The API hasn't changed but there are a bunch of improvements that are currently forcing us to pin git versions:

 - Better error messages from 94134f76ae102a6a4de6e6a789dd011dd106bf78 and https://github.com/kennknowles/ocaml-freetds/commit/bdc2c991cfaafd878339c30f8d7265c51668bc2d
 - dylib support from #14 
 - A fix to Dblib.count from #17

**Comment by Chris00** [comment]
@kennknowles May you activate the gh-pages so one can [read the documentation online](https://kennknowles.github.io/ocaml-freetds/doc)?  Thanks.

**Comment by Chris00** [comment]
PR pending https://github.com/ocaml/opam-repository/pull/11797
