### ISSUE TITLE
Convert to ctypes

### ISSUE THREAD

**Issue by brendanlong** [kennknowles/ocaml-freetds#23]
Some of our code is kind of complicated because we're doing things like throwing exceptions in OCaml. It would be nice if we could just use ctypes and have bindings to dbopen, dbdatalen, etc. generated and then do all of the logic in OCaml.

**Comment by Chris00** [comment]
I am not sure it is worth the work.  Also, the C interface comes with OCaml, gives complete control, and is battle tested.  I'm also not sure it is that complicated.  May you be more specific?

**Comment by brendanlong** [comment]
#20 Throws much worse exceptions than I'd like to because sprintf and dealing with tracking C strings isn't something I want to deal with, but in OCaml it would be trivial to include column numbers and data types in the exception messages. It also allocates space for 0-length strings because I don't what to think about the complexity of sometimes returning constant empty-strings and sometimes returning allocated non-empty strings in C.

**Comment by Chris00** [comment]
I [have split](https://github.com/Chris00/ocaml-freetds) the binding into smaller parts which allows to improve the error messages.  Note that things are somewhat complicated by the fact that there is an error handler and the exceptions we throw should ideally be compatible with it...

**Comment by brendanlong** [comment]
Thanks! It looks like with the changes you made recently I probably won't need to do much with this anyway
