### ISSUE TITLE
Handle '' (empty string) properly

### ISSUE THREAD

**Issue by Chris00** [kennknowles/ocaml-freetds#24]
This is a problem with the upstream `dblib`.  Indeed, with the request (see [tests](https://github.com/Chris00/ocaml-freetds/blob/master/test/test_dblib.ml#L125-L144))
```sql
SELECT c1, LEN(c1), c2, c3, c4 FROM #test
```
I have [the error](https://ci.appveyor.com/project/Chris00/ocaml-freetds/build/1.0.62#L511):
```
expected: STRING(""), INT(0), STRING(""), INT(-1), FLOAT(-6.300000)
- but got: STRING(" "), INT(0), STRING(" "), INT(-1), FLOAT(-6.300000)
```
which clearly shows that the database (rightly) thinks that the data has length `0` but `dbdatlen` returns `1`.

**Comment by Chris00** [comment]
The problem may well come from the [following fix](https://sourceforge.net/p/freetds/bugs/25/#4850).

**Comment by Chris00** [comment]
Maybe the solution is to leave `Dblib` as it is (with a warningà and see whether `Ct` has the same issue.

**Comment by Chris00** [comment]
Unfortunately the library `Ct` [has the same problem](https://ci.appveyor.com/project/Chris00/ocaml-freetds/build/1.0.74#L487).  Reported [upstream](https://github.com/FreeTDS/freetds/issues/212).

**Comment by Chris00** [comment]
All `Dblib` and `ct` tests [pass](https://ci.appveyor.com/project/Chris00/ocaml-freetds#L481).  It seems there is no way to set the _protocol_ version through the C code.  I explained how to use environment variables (`freetds.conf` is also possible).

@brendanlong May you confirm this also fixes the problem on your side?

**Comment by brendanlong** [comment]
Ahh that makes sense. Maybe our internal CI server was using a lower protocol than my new Fedora machine. I'll check if we see this, but now that I know what's going on we can probably just enforce a higher protocol. Thanks for looking into this!

**Comment by Chris00** [comment]
Note that I was not happy with the way `~version` worked — I found it pretty much useless.  I am in the process of converting it to set `DBSETLVERSION` (note the `L`) which will set the protocol.  It works for [setting the version](https://ci.appveyor.com/project/Chris00/ocaml-freetds/build/1.0.102#L485) the version) — the fact that only the `Ct` tests fail means that the default version is too low but `Dblib` is OK because it sets it.  However it [is superseded](https://ci.appveyor.com/project/Chris00/ocaml-freetds/build/1.0.103#L502) by `TDSVER` if the latter is set.  (@brendanlong I have not tested with `freetds.conf`, pease do and update the documentation if you have time.)

**Comment by brendanlong** [comment]
Hm yeah so due to various bits of weirdness with Amazon Linux and our database, I ended up removing V73 and V74 (FreeTDS 1.0-only) and hard-coding our internal library to use protocol version 7.1, but now it works right! :D I'm guessing the reason this worked on my laptop is that it runs FreeTDS 1.0 and was automatically picking a sane version by default.

**Comment by Chris00** [comment]
On 29 May 2018 at 15:29 GMT, Brendan Long wrote:
>
> Hm yeah so due to various bits of weirdness with Amazon Linux and our
> database, I ended up removing V73 and V74 (FreeTDS 1.0-only)

Why so?  There is no default set by Dblib, you can leave theses options (you do not need to exercise them).

> […] internal library to use protocol version 7.1,

Do you think we should have a global variable to set the default protocol version for all connections?  Or it the environment variable enough?

> but now it works right! […]

Glad that it does!

**Comment by brendanlong** [comment]
That version works for us :)
