### ISSUE TITLE
Enable AppVeyor

### ISSUE THREAD

**Issue by Chris00** [kennknowles/ocaml-freetds#25]
@kennknowles Could you enable AppVeyor from your account?  I will look more “normal” that the badge points to your AppVeyor account...

**Comment by kennknowles** [comment]
Acknowledging receipt of this issue. I am unfamiliar so I'll comment back here if I get confused about this.

**Comment by kennknowles** [comment]
OK I have authorized it and set it up for this project I believe. It seems to take permissions from GitHub, but I'm not sure how they are mapped.

Would it perhaps be helpful to migrate this project to an "Organization" so it can have multiple owners and administrators?

**Comment by Chris00** [comment]
It seems the build can be monitored at https://ci.appveyor.com/project/kennknowles/ocaml-freetds  Could you push the button to start a new build?  Could you also look to the settings for the badge markdown code?

**Comment by kennknowles** [comment]
Looks like there have been a few builds. I pushed the button anyhow. Here is the image URL: https://ci.appveyor.com/api/projects/status/7mk4ksdqea78gqoh/branch/master

[![Build status](https://ci.appveyor.com/api/projects/status/7mk4ksdqea78gqoh/branch/master?svg=true)](https://ci.appveyor.com/project/kennknowles/ocaml-freetds/branch/master)
