### ISSUE TITLE
Add depext section to the opam file

### ISSUE THREAD

**Issue by brendanlong** [kennknowles/ocaml-freetds#9]
I would open a pull request but I can't find the opam file.

[depext](https://github.com/ocaml/opam-depext) lets you list the system dependencies for an OCaml library, so it would be nice if the opam file had a section like:

```
depexts: [
  [["alpine"] ["freetds-dev"]]
  [["centos"] ["freetds-devel"]]
  [["debian"] ["freetds-dev"]]
  [["fedora"] ["freetds-devel"]]
  [["homebrew"] ["freetds"]]
  [["ubuntu"] ["freetds-dev"]]
]
```

With that, `opam depext freetds` will install the development headers for FreeTDS automatically.

**Comment by Chris00** [comment]
Yes, an opam file should be created in the repository — and the structure put in place to help making new releases.
